# Generated by Django 5.0.6 on 2024-06-14 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер заказа')),
                ('name_customer', models.CharField(max_length=50, verbose_name='Имя покупателя')),
                ('lastname_customer', models.CharField(max_length=50, verbose_name='Фамилия покупателя')),
                ('surname_customer', models.CharField(blank=True, max_length=50, null=True, verbose_name='Очество покупателя')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментаций')),
                ('adress', models.TextField(verbose_name='Адрес доставки')),
                ('method_delivery', models.TextField(verbose_name='Способ доставки')),
                ('create_data', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('end_data', models.DateField(auto_now=True, null=True, verbose_name='Дата завершения')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('create_data', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_data', models.DateField(auto_now=True, verbose_name='Дата изменения')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d', verbose_name='Фото обложки')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['name', '-price'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('name_provider', models.CharField(max_length=50, verbose_name='Имя представителя')),
                ('lastname_provider', models.CharField(max_length=50, verbose_name='Фамилия представителя')),
                ('surname_provider', models.CharField(blank=True, max_length=50, null=True, verbose_name='Очество представителя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон представителя')),
                ('adress', models.TextField(verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Сharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('characteristic', models.TextField(verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.CreateModel(
            name='Position_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('discount', models.IntegerField(blank=True, null=True, verbose_name='Скидка')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='about.order', verbose_name='Заказ')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='about.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('product', models.ManyToManyField(to='about.product')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Supplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер поставки')),
                ('date_supplies', models.DateField(auto_now_add=True, verbose_name='Дата поставки')),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='about.provider', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Поставка',
                'verbose_name_plural': 'Поставки',
            },
        ),
        migrations.CreateModel(
            name='Position_supplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Кол-во товара')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='about.product', verbose_name='Товар')),
                ('supplies', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='about.supplies', verbose_name='Поставка')),
            ],
            options={
                'verbose_name': 'Позиция поставки',
                'verbose_name_plural': 'Позиция поставок',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('desctiption', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('product', models.ManyToManyField(to='about.product')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Full_Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=255, verbose_name='Значение')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='about.product', verbose_name='Товар')),
                ('characteristic', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='about.сharacteristic', verbose_name='Характеристика товара')),
            ],
            options={
                'verbose_name': 'Характеристи товаров',
            },
        ),
    ]
