# Generated by Django 5.0.6 on 2024-06-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_product_exists'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Position_order',
            new_name='PositionOrder',
        ),
        migrations.RenameModel(
            old_name='Position_supplies',
            new_name='PositionSupplies',
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d', verbose_name='Фотография блюда'),
        ),
    ]
